/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.JOptionPane;
// import javax.swing.*;
// import java.util.*;
/**
 *
 * @author ArfaatAli
 */
public class calulator1 extends javax.swing.JFrame {

    /**
     * Creates new form calulator1
     */
    public calulator1() {
        initComponents();
    }
    int gp;
    String gr;
    
    String [] subject = new String[10];
    int [] obmark = new int[10];
    String [] grade = new String[10];
    int [] gpa = new int[10];
    int i=0;
    public int FindGP(int mrk)
        {
           // use of conditional statement (if else)
            if (mrk >= 80 & mrk <= 100)
            {
                gp = 4;               
            }
            else if (mrk >= 65 & mrk <= 79)
            {
                gp = 3;                
            }
            else if (mrk >= 50 & mrk <= 64)
            {
                gp = 2;               
            }
            else if (mrk >= 40 & mrk <= 49)
            {
                gp = 1;            
            }
            else if (mrk < 40)
            {
                gp = 0;                
            }
            return gp;       
        }
 
        // use of functions  (Function declation and definition)
        public String FindGrade(int mrk)
        {
            // use of conditional statement (if else)

            if (mrk >= 80 & mrk <= 100)
            {
                gr = "A";
            }
            else if (mrk >= 65 & mrk <= 79)
            {
                gr = "B";
            }
            else if (mrk >= 50 & mrk <= 64)
            {
                gr = "C";
          }
            else if (mrk >= 40 & mrk <= 49)
            {
                gr = "D";
            }
            else if (mrk < 40)
            {
                gr = "F";
            }

            return gr;
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gp6 = new javax.swing.JLabel();
        finalgpa = new javax.swing.JLabel();
        gp5 = new javax.swing.JLabel();
        mar4 = new javax.swing.JLabel();
        subject5 = new javax.swing.JLabel();
        mar2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        remarks = new javax.swing.JLabel();
        mar1 = new javax.swing.JLabel();
        grd1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        mar5 = new javax.swing.JLabel();
        obmarks = new javax.swing.JTextField();
        mar6 = new javax.swing.JLabel();
        subjectcode = new javax.swing.JTextField();
        gp3 = new javax.swing.JLabel();
        subject6 = new javax.swing.JLabel();
        grd5 = new javax.swing.JLabel();
        grd4 = new javax.swing.JLabel();
        grd3 = new javax.swing.JLabel();
        grd2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        grd6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        gp1 = new javax.swing.JLabel();
        gp2 = new javax.swing.JLabel();
        subject3 = new javax.swing.JLabel();
        gp4 = new javax.swing.JLabel();
        subject4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        subject1 = new javax.swing.JLabel();
        subject2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        mar3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        stdname = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbname = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        gp6.setText("-");

        finalgpa.setText("-");

        gp5.setText("-");

        mar4.setText("-");

        subject5.setText("-");

        mar2.setText("-");

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        remarks.setText("-");

        mar1.setText("-");

        grd1.setText("-");

        jLabel4.setText("Obtained Marks % :");

        jLabel5.setText("Subject Code :");

        mar5.setText("-");

        obmarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obmarksActionPerformed(evt);
            }
        });

        mar6.setText("-");

        gp3.setText("-");

        subject6.setText("-");

        grd5.setText("-");

        grd4.setText("-");

        grd3.setText("-");

        grd2.setText("-");

        jLabel11.setText("Subject");

        grd6.setText("-");

        jLabel10.setText("Marks");

        gp1.setText("-");

        gp2.setText("-");

        subject3.setText("-");

        gp4.setText("-");

        subject4.setText("-");

        jLabel9.setText("Remarks : ");

        subject1.setText("-");

        subject2.setText("-");

        jButton2.setText("Result");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Grade");

        jLabel8.setText("GPA :");

        mar3.setText("-");

        jLabel7.setText("Grade Point");

        jLabel1.setText("Student Name : ");

        jLabel3.setText("Student Name : ");

        lbname.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(75, 75, 75)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel8))
                            .addGap(48, 48, 48)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(remarks)
                                .addComponent(finalgpa))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(55, 55, 55)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbname))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(9, 9, 9)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(subject1)
                                                .addComponent(subject2)
                                                .addComponent(subject3)
                                                .addComponent(subject4)
                                                .addComponent(subject5)
                                                .addComponent(subject6))))
                                    .addGap(52, 52, 52)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(mar1)
                                                .addComponent(mar2)
                                                .addComponent(mar3)
                                                .addComponent(mar4)
                                                .addComponent(mar5)
                                                .addComponent(mar6))
                                            .addGap(9, 9, 9)))
                                    .addGap(54, 54, 54)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(grd5, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(grd6))
                                                .addComponent(grd3)
                                                .addComponent(grd2)
                                                .addComponent(grd1)
                                                .addComponent(grd4))
                                            .addGap(11, 11, 11)))))
                            .addGap(51, 51, 51)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(11, 11, 11)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(gp1)
                                        .addComponent(gp2)
                                        .addComponent(gp3)
                                        .addComponent(gp5)
                                        .addComponent(gp6)
                                        .addComponent(gp4))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(obmarks, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(stdname)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(name)
                                        .addGap(4, 4, 4))
                                    .addComponent(subjectcode))
                                .addGap(34, 34, 34)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(jButton2)))))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stdname))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(subjectcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(obmarks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jButton1)))
                .addGap(28, 28, 28)
                .addComponent(jButton2)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subject1)
                    .addComponent(mar1)
                    .addComponent(grd1)
                    .addComponent(gp1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subject2)
                    .addComponent(mar2)
                    .addComponent(grd2)
                    .addComponent(gp2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subject3)
                    .addComponent(mar3)
                    .addComponent(grd3)
                    .addComponent(gp3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subject4)
                    .addComponent(mar4)
                    .addComponent(grd4)
                    .addComponent(gp4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mar5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(subject5)
                        .addComponent(grd5)
                        .addComponent(gp5)))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subject6)
                    .addComponent(mar6)
                    .addComponent(grd6)
                    .addComponent(gp6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(finalgpa))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(remarks))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String nm;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // TODO add your handling code here:

        // use of arrays (Store values in arrays)
        
        if(!"".equals(name.getText()))
        {
        if(!"".equals(subjectcode.getText()))
        {
            if(!"".equals(obmarks.getText()))
        {
            if(i<6){
                
                nm = (String) name.getText();
                stdname.setText(nm);
                name.setVisible(false);
        obmark[i] = Integer.parseInt(obmarks.getText());
        subject[i] =  (String) subjectcode.getText();
        grade[i] = FindGrade(obmark[i] );
        gpa[i] = FindGP(obmark[i] );
        ++i;

        subjectcode.setText(String.valueOf(""));
        obmarks.setText(String.valueOf(""));
            }
            else 
            {
            
            JOptionPane.showMessageDialog(null, "You can enter maximum 6 subjects");
            subjectcode.setText(String.valueOf(""));
            obmarks.setText(String.valueOf(""));
            }
        }
            else {
            
            JOptionPane.showMessageDialog(null, "Please enter marks");
            
            }
        }
        else 
        {
        JOptionPane.showMessageDialog(null, "Please enter subject code");
        
        }
        }
        else {
    
    JOptionPane.showMessageDialog(null, "Please enter Student name ");
    }
        // Clearing the text boxes
    }//GEN-LAST:event_jButton1ActionPerformed

    private void obmarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obmarksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_obmarksActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        // TODO add your handling code here:
        lbname.setText(nm);
        subject1.setText(String.valueOf(subject[0]));
        subject2.setText(String.valueOf(subject[1]));
        subject3.setText(String.valueOf(subject[2]));
        subject4.setText(String.valueOf(subject[3]));
        subject5.setText(String.valueOf(subject[4]));
        subject6.setText(String.valueOf(subject[5]));

        mar1.setText(String.valueOf(obmark[0]));
        mar2.setText(String.valueOf(obmark[1]));
        mar3.setText(String.valueOf(obmark[2]));
        mar4.setText(String.valueOf(obmark[3]));
        mar5.setText(String.valueOf(obmark[4]));
        mar6.setText(String.valueOf(obmark[5]));

        grd1.setText(String.valueOf(grade[0]));
        grd2.setText(String.valueOf(grade[1]));
        grd3.setText(String.valueOf(grade[2]));
        grd4.setText(String.valueOf(grade[3]));
        grd5.setText(String.valueOf(grade[4]));
        grd6.setText(String.valueOf(grade[5]));

        gp1.setText(String.valueOf(gpa[0]));
        gp2.setText(String.valueOf(gpa[1]));
        gp3.setText(String.valueOf(gpa[2]));
        gp4.setText(String.valueOf(gpa[3]));
        gp5.setText(String.valueOf(gpa[4]));
        gp6.setText(String.valueOf(gpa[5]));

        int tgpa =0;
        double gpa1 = 0.0;
        String Rem = "";
        for (int j = 0; j < 6; j++)
        {
            tgpa += gpa[j];
            double b = (double) i;

            gpa1 = tgpa / b;
        }

        // Show the GPA  Integer.parseInt(obmarks.getText());
        finalgpa.setText(String.valueOf(gpa1));
        int i = (int) gpa1;

        // use of conditional statement (Switch used to assign remarks according to GPA)
        switch (i)
        {

            case 4:
            Rem = "Excellent";
            break;
            case 3:
            Rem = "Good";
            break;
            case 2:
            Rem = "Satisfactory";
            break;
            case 1:
            Rem = "pass";
            break;

            case 0:
            Rem = "Fail";
            break;
        }
        // Show Remarks
        remarks.setText(String.valueOf(Rem));
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calulator1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calulator1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calulator1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calulator1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calulator1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel finalgpa;
    private javax.swing.JLabel gp1;
    private javax.swing.JLabel gp2;
    private javax.swing.JLabel gp3;
    private javax.swing.JLabel gp4;
    private javax.swing.JLabel gp5;
    private javax.swing.JLabel gp6;
    private javax.swing.JLabel grd1;
    private javax.swing.JLabel grd2;
    private javax.swing.JLabel grd3;
    private javax.swing.JLabel grd4;
    private javax.swing.JLabel grd5;
    private javax.swing.JLabel grd6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbname;
    private javax.swing.JLabel mar1;
    private javax.swing.JLabel mar2;
    private javax.swing.JLabel mar3;
    private javax.swing.JLabel mar4;
    private javax.swing.JLabel mar5;
    private javax.swing.JLabel mar6;
    private javax.swing.JTextField name;
    private javax.swing.JTextField obmarks;
    private javax.swing.JLabel remarks;
    private javax.swing.JLabel stdname;
    private javax.swing.JLabel subject1;
    private javax.swing.JLabel subject2;
    private javax.swing.JLabel subject3;
    private javax.swing.JLabel subject4;
    private javax.swing.JLabel subject5;
    private javax.swing.JLabel subject6;
    private javax.swing.JTextField subjectcode;
    // End of variables declaration//GEN-END:variables
}
